name: Run linter and tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v2
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
